version: '3.8'
services:
  frontendapp:
    build: ./frontendapp
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    container_name: "frontendapp"
    env_file:
      - .env
    environment:
      - PORT=${FRONT_PORT}

  backendapp:
    build: ./backendapp
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    container_name: "backendapp"
    env_file:
      - .env
    environment:
      - PORT=${BACK_PORT}

  db:
    image: postgres:13
    container_name: "postgresdb"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

volumes:
  postgres-data:
